# Generated by Django 4.2.2 on 2023-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0006_comment_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_data_backup',
            field=models.TextField(default=''),
        ),
    ]
